name: notify_offduty
on:
  schedule:
    - cron: "30 3 * * *"
jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request
        run: |
          curl "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECHATBOTKEY }}" -H 'Content-Type: application/json' -d '{"msgtype":"text","text":{"content": "午休结束"}}'
