name: Scheduled POST Request
on:
  schedule:
    - cron: "55 9 * * *"

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST Request
        env:
          MY_KEY: ${{ secrets.WECHATBOTKEY }}
        run: |
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${MY_KEY}' -H 'Content-Type: application/json' -d '{"msgtype":"text","text":{"content": "准备下班！！！"}}'
